### ISSUE TITLE
Error with raft-start.sh

### ISSUE THREAD

**Issue by yjfcn** [jpmorganchase/quorum-examples#57]
When I run raft-init.sh, no problem. After that, I run raft-start.sh, it shows the error:
Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory
I checked the folder qdata/dd1, there is no file named geth.ipc.
Did I miss something?

**Comment by sahar-fehri** [comment]
I keep getting the same error too ..

**Comment by sahar-fehri** [comment]
Do vagrant destroy and vagrant up . It should work now .

**Comment by antonmok** [comment]
Still getting this error:
Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory

**Comment by abhayar** [comment]
I'm also getting the same error:
Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory
I checked the folder qdata/dd1, there is no file named geth.ipc.

**Comment by fedealconada** [comment]
Any news about this?

**Comment by patrickmn** [comment]
Is this still occurring with the latest quorum-examples?

**Comment by yjfcn** [comment]
it's fixed. The reason is some library is missing.
