### ISSUE TITLE
7nodes error on private.get()

### ISSUE THREAD

**Issue by aathorson** [jpmorganchase/quorum-examples#79]
**Version**:
Geth
Version: 1.7.2-stable
Git Commit: 2a5a1d6146e38b7025868ad0cfa183f42de3554e
Quorum Version: 2.0.0
Architecture: amd64
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

**Context**
After running the 7nodes example on terminal 1, node7 can't see the initialized value.

**Expected output**:
In terminal window 1 (node 1) 
> private.get()
42
In terminal window 2 (node 4) :
> private.get()
0
In terminal window 3 (node 7) :
> private.get()
42

**Actual output:**
In terminal window 1 (node 1) :
> private.get()
42
In terminal window 1 (node 1) :
> private.get()
0
In terminal window 1 (node 1) :
> private.get()
0

![7nodes-error](https://user-images.githubusercontent.com/36660288/36476989-e19c86fa-16ff-11e8-9f5d-673564a56d19.png)

**Comment by haxgalax** [comment]
I am experiencing the same issue.

**Comment by adfortia** [comment]
Same issue too.
In qdata/logs/constellation7.log I find this line:

`17:31:45 [WARN] Error performing API request: ApiReceiveRaw (Receive {rreqKey = "eyJrZXkiOiJqUGxqb1l1WkJ3QW5RV0gzczA4emJvTXJDK0YzajlNMWkwU3NLZUdFVFVRYWpFVkFSdXVDYzZ6bEU2NmY2UERYUkQxZjFvR3QwWHZ5b1V1RUQzOHZQQT09In0=", rreqTo = Nothing}); Payload not found in directory storage: storage/payloads/PMRGWZLZEI5CE2SQNRVG6WLVLJBHOQLOKFLUQM3TGA4HUYTPJVZEGK2GGNVDSTJRNEYFG42LMVDUKVCVKFQWURKWIFJHK5KDMM3HU3CFGY3GMNSQIRMFERBRMYYW6R3UGBMHM6LPKV2UKRBTHB3FAQJ5HURH2===: openBinaryFile: does not exist (No such file or directory)`

In that folder there is only a file named "RT4WHIMLTEDQAJ2BMH33GTZTN2BSWC7BO6H5GNMLISWCTYMEJVCBVDCFIBDOXATTVTSRHLU75DYNORB5L7LIDLORPPZKCS4EB57S6PA="

Is this a constellation issue?

Hope this helps.

**Comment by patrickmn** [comment]
This is an issue with the switch to the raw send/receive methods (Quorum is expecting an unencoded identifier and Constellation is returning Base64.) The integration should have been tested more carefully.

Will push a change to either Quorum or Constellation shortly.

**Comment by patrickmn** [comment]
Fixed by https://github.com/jpmorganchase/quorum/commit/ee498061b5a74bf1f3290139a53840345fa038cb and https://github.com/jpmorganchase/constellation/commit/3d9e4f05499c7aad7c02cde5b4538b9216e94211

Please use the latest quorum-examples vagrant image which includes Quorum 2.0.1 and Constellation 0.3.2.

**Comment by anidhya** [comment]
I am still facing this issue.
I installed through source. Using master branch of quorum and latest binary from constellation.
How can I debug whats wrong here?
